
NDefines.NGraphics.MINIMUM_PROVINCE_SIZE_IN_PIXELS = 1
NDefines.NGraphics.COUNTRY_FLAG_TEX_MAX_SIZE = 512
NDefines.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 256
NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_HEIGHT = 2048
NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_HEIGHT = 8000